require("config.hyprland.monitors")
pcall(require, "config.hyprland.monitors_local")
require("config.hyprland.autostart")
pcall(require, "config.hyprland.autostart_local")
require("config.hyprland.env")
pcall(require, "config.hyprland.env_local")
require("config.hyprland.permissions")
pcall(require, "config.hyprland.permissions_local")
require("config.hyprland.look-and-feel")
pcall(require, "config.hyprland.look-and-feel_local")
require("config.hyprland.input")
pcall(require, "config.hyprland.input_local")
require("config.hyprland.keybinds")
pcall(require, "config.hyprland.keybinds_local")
require("config.hyprland.workspaces")
pcall(require, "config.hyprland.workspaces_local")
