#!/bin/bash

export SXHKD_SHELL=/bin/bash
pgrep -x sxhkd >/dev/null || sxhkd &

pkill -USR1 -x sxhkd

# bspc monitor -d I II III IV V VI VII VIII IX X
i=1
for monitor in $(bspc query -M); do
    bspc monitor $monitor \
        --reset-desktops $i/{1..9}
    #--rename "$monitor" \
    # --reset-desktops "$monitor"/{1..9}
    let i++
done

bspc config border_width 2
bspc config window_gap 4
#bspc config normal_border_color   '#000000'
bspc config focused_border_color '#8E24AA'

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Media players
bspc rule -a mpv state=floating
bspc rule -a vlc state=floating

# Image viewers
bspc rule -a nomacs state=floating
bspc rule -a 'Image Lounge' state=floating
bspc rule -a qimgv state=floating
bspc rule -a feh state=floating
bspc rule -a mirage state=floating
bspc rule -a Mirage state=floating
bspc rule -a ristretto state=floating
bspc rule -a copyq state=floating

# Fixes
bspc rule -a Emacs state=tiled

# Autostart stuff
"$(dirname $0)"/autorun.sh
