# Media players
windowrule = float yes, persistent_size yes, match:class mpv
windowrule = float yes, persistent_size yes, match:class vlc
# Image viewers
windowrule = float yes, persistent_size yes, match:class nomacs
windowrule = float yes, persistent_size yes, match:class 'Image Lounge'
windowrule = float yes, persistent_size yes, match:class qimgv
windowrule = float yes, persistent_size yes, match:class feh
windowrule = float yes, persistent_size yes, match:class mirage
windowrule = float yes, persistent_size yes, match:class Mirage
windowrule = float yes, persistent_size yes, match:class ristretto
windowrule = float yes, persistent_size yes, match:class copyq
windowrule = float yes, persistent_size yes, match:class minecraft-launcher
windowrule = float yes, persistent_size yes, match:class flameshot
windowrule = float yes, persistent_size yes, match:class xdg-desktop-portal-gtk
# Fixes
windowrule = tile yes, match:class Emacs
# XWayland
windowrule = opacity 0.0 override, match:class ^(xwaylandvideobridge)$
windowrule = no_anim yes, match:class ^(xwaylandvideobridge)$
windowrule = no_initial_focus yes, match:class ^(xwaylandvideobridge)$
windowrule = max_size 1 1, match:class ^(xwaylandvideobridge)$
windowrule = no_blur yes, match:class ^(xwaylandvideobridge)$
windowrule = no_focus yes, match:class ^(xwaylandvideobridge)$

