# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/


###################
### MY PROGRAMS ###
###################
# Set programs that you use
$terminal = ghostty
$fileManager = dolphin
$menu = wofi --show drun


################
### MONITORS ###
################
source = ~/.config/hypr/conf.d/hyprland/monitors.conf
# hyprlang noerror true
source = ~/.config/hypr/conf.d/hyprland/monitors.local.conf
# hyprlang noerror false


#################
### AUTOSTART ###
#################
source = ~/.config/hypr/conf.d/hyprland/autostart.conf
# hyprlang noerror true
source = ~/.config/hypr/conf.d/hyprland/autostart.local.conf
# hyprlang noerror false


#############################
### ENVIRONMENT VARIABLES ###
#############################
source = ~/.config/hypr/conf.d/hyprland/env.conf
# hyprlang noerror true
source = ~/.config/hypr/conf.d/hyprland/env.local.conf
# hyprlang noerror false


###################
### PERMISSIONS ###
###################
source = ~/.config/hypr/conf.d/hyprland/permissions.conf
# hyprlang noerror true
source = ~/.config/hypr/conf.d/hyprland/permissions.local.conf
# hyprlang noerror false


#####################
### LOOK AND FEEL ###
#####################
source = ~/.config/hypr/conf.d/hyprland/look-and-feel.conf
# hyprlang noerror true
source = ~/.config/hypr/conf.d/hyprland/look-and-feel.local.conf
# hyprlang noerror false


#############
### INPUT ###
#############
source = ~/.config/hypr/conf.d/hyprland/input.conf
# hyprlang noerror true
source = ~/.config/hypr/conf.d/hyprland/input.local.conf
# hyprlang noerror false


###################
### KEYBINDINGS ###
###################
source = ~/.config/hypr/conf.d/hyprland/keybinds.conf
# hyprlang noerror true
source = ~/.config/hypr/conf.d/hyprland/keybinds.local.conf
# hyprlang noerror false


##############################
### WINDOWS AND WORKSPACES ###
##############################
source = ~/.config/hypr/conf.d/hyprland/workspaces.conf
# hyprlang noerror true
source = ~/.config/hypr/conf.d/hyprland/workspaces.local.conf
# hyprlang noerror false

