# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = waybar & hyprpaper & firefox

exec-once = nm-applet
exec-once = waybar
# exec-once = swaybg --mode fill --image ~/wallpapers/defalt.jpg
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Start Polkit
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once = systemctl --user start hyprpolkitagent

# Load Notification Daemon
exec-once = swaync

# # Using hypridle to start hyprlock
# exec-once = hypridle
# exec-once = sway-audio-idle-inhibit
exec-once = stasis

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Application launcher daemon
exec-once = vicinae server

exec = hyprpm reload -n

exec-once = hypridle
exec-once = hyprsunset
