input {
    kb_layout = us,hr
    kb_variant =
    kb_model =
    kb_options = caps:escape,grp:win_space_toggle,fkeys:basic_13-24
    kb_rules =

    repeat_rate = 50
    repeat_delay = 250

    numlock_by_default = true

    accel_profile = flat
    sensitivity = 0.4 # -1.0 - 1.0, 0 means no modification.

    follow_mouse = 2
    mouse_refocus = false
    float_switch_override_focus = false

    touchpad {
        natural_scroll = true
    }
}

gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
# device {
#     name = epic-mouse-v1
#     sensitivity = -0.5
# }
