# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*
windowrule = float yes, match:modal yes

# Fix some dragging issues with XWayland
windowrule = no_focus yes, match:class ^$, match:title ^$, match:xwayland yes, match:float yes, match:fullscreen no, match:pin no

windowrule = idle_inhibit fullscreen, match:class ^(*)$
windowrule = idle_inhibit fullscreen, match:title ^(*)$
windowrule = idle_inhibit fullscreen, match:fullscreen true

layerrule = blur yes, match:modal yes

# Vicinae
# TODO: FIX THIS
# layerrule = blur yes, match:vicinae yes
# layerrule = blur,vicinae
# layerrule = ignorealpha 0, vicinae
# layerrule = noanim, vicinae

